### ISSUE TITLE
When toggling the hud it won't re open after being closed

### ISSUE THREAD

**Issue by IgnornceIsBliss** [hasidu/fh4speed-MODIFIED#1]
function ToggleDisplay()
	if isHide then
		isHide = false
		SendNUIMessage({
			ShowHud                = true,
		})
	else
		SendNUIMessage({HideHud = true})
		isHide = true
	end
end

This seems to update it to show again but is buggy :(

**Comment by hasidu** [comment]
hi @JackDUpModZ thanks for update i will check it and let you now

**Comment by hasidu** [comment]
hi checked all things its seems all working well when you press f10 its hide and if you press it again f10 it will show.
